### ISSUE TITLE
ツールバーに実行結果クリアボタンを設ける

### ISSUE THREAD

**Issue by myamamoto** [ChangeVision/astah-script-plugin#13]

**Comment by myamamoto** [comment]
クリア機能ありました。

**Comment by myamamoto** [comment]
![remove](https://cloud.githubusercontent.com/assets/1323775/20950541/aa9d1a9a-bc63-11e6-9a0e-7f0d715600a0.png)

**Comment by takahiro-fujito-cv** [comment]
実行ボタン横にコンソールをクリアするボタンを作成しました。
また、ボタンを押した時にステータスバーに「Console cleared」「コンソールをクリアしました」と表示されるようにmessages.propertiesとmessages_ja.propertiesの中身にメッセージを追加しClearOutputCommandの中にメッセージを表示する行を追加しました。

**Comment by takahiro-fujito-cv** [comment]
<img width="555" alt="13_image" src="https://cloud.githubusercontent.com/assets/23517825/21008976/9566023e-bd87-11e6-887d-7bb9ec045849.png">
