### ISSUE TITLE
実行時に実行結果画面をクリア可能とする

### ISSUE THREAD

**Issue by myamamoto** [ChangeVision/astah-script-plugin#14]
オプション画面を、メニューとツールボタンから表示。
設定内容は保存し、次回起動時にもリロードされること。

**Comment by takahiro-fujito-cv** [comment]
テスト項目
![default](https://cloud.githubusercontent.com/assets/23517825/21515645/e84ddc82-cd14-11e6-88da-e39e9b8b770d.png)
